version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
    restart: unless-stopped
    networks:
      my-web-page:
        ipv4_address: 15.0.2.5
  web1:
    image: nginx:latest
    volumes:
      - ./web1/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    networks:
      my-web-page:
        ipv4_address: 15.0.2.6
  web2:
    image: nginx:latest
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    networks:
      my-web-page:
        ipv4_address: 15.0.2.7

networks:
  my-web-page:
    driver: bridge
    ipam:
      config:
        - subnet: 15.0.2.0/24